version: "3"

services:
  apache:
    build:
      dockerfile: php7-apache2-dockerfile
      context: .
    container_name: php7-apache2
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysqlDB
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=MyDatabase
      - MYSQL_DATABASE=library

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:8081"
    environment:
      - PMA_ARBITRARY=1
